version: 2

sources:
  - name: src
    schema: landing
    tables:
      - name: ecomm_audit_log_dml
        description: "An input layer for audit_log_dml_data"
        columns:
          - name: ingested_at
            description: "The time when the record was ingested into Iceberg"
            tests:
              - not_null
          - name: source_file
            description: "Path to the source s3 object"
            tests:
              - not_null
          - name: audit_event_id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: audit_timestamp
            description: "The time when the event occurred"
            tests:
              - not_null
          - name: audit_operation
            description: "What kind of operation was performed"
          - name: tbl_schema
            description: "The table schema"
          - name: tbl_name
            description: "The Table name"
          - name: raw_data
            description: "A raw data in json format"