CREATE TABLE IF NOT EXISTS ride_bookings (
    booking_date DATE NOT NULL,
    booking_time TIME NOT NULL,
    booking_id TEXT,
    booking_status TEXT,
    customer_id TEXT,
    vehicle_type TEXT,
    pickup_location TEXT,
    drop_location TEXT,
    avg_vtat NUMERIC,
    avg_ctat NUMERIC,
    cancelled_rides_by_customer INT,
    reason_for_cancelling_by_customer TEXT,
    cancelled_rides_by_driver INT,
    driver_cancellation_reason TEXT,
    incomplete_rides INT,
    incomplete_rides_reason TEXT,
    booking_value NUMERIC,
    ride_distance NUMERIC,
    driver_ratings NUMERIC,
    customer_rating NUMERIC,
    payment_method TEXT,
    primary key (booking_id, customer_id)
);