dbt_dwh:
  outputs:
    duckdb_iceberg:
      type: duckdb
      path: "/opt/airflow/data/iceberg.duckdb"
      database: iceberg
      schema: landing
      threads: 1
#      disable_transactions: true
      extensions:
        - httpfs
        - iceberg

    # use for in-memory development
    duckdb_memory:
      type: duckdb
      path: ":memory:"
      database: memory
      schema: landing
      threads: 1
      extensions:
        - httpfs
        - iceberg

  target: duckdb_iceberg