version: 2

models:
  - name: orders
    description: "Current state table - latest version of each order (excludes deleted)"
    config:
      contract:
        enforced: true
    columns:
      - name: ingested_at
        data_type: timestamp(6) with time zone
        description: "When this record was ingested into the data lake"
        tests:
          - not_null
      - name: source_file
        data_type: varchar
        description: "Source CSV file name"
      - name: audit_event_id
        data_type: bigint
        description: "Unique identifier for the audit event"
        tests:
          - not_null
      - name: audit_operation
        data_type: varchar
        description: "Type of operation: I (Insert), U (Update)"
        tests:
          - not_null
          - accepted_values:
              values: ['I', 'U']
      - name: audit_timestamp
        data_type: timestamp(6) with time zone
        description: "When this version of the order was created"
        tests:
          - not_null
      - name: tbl_schema
        data_type: varchar
        description: "Schema of the source table"
        tests:
          - not_null
      - name: tbl_name
        data_type: varchar
        description: "Name of the source table"
        tests:
          - not_null
      - name: order_id
        data_type: integer
        description: "Primary key - unique order identifier"
        tests:
          - unique
          - not_null
      - name: order_timestamp
        data_type: timestamp(6) with time zone
        description: "When the order was placed"
      - name: created_at
        data_type: timestamp(6) with time zone
        description: "When the order record was created"
      - name: updated_at
        data_type: timestamp(6) with time zone
        description: "When the order record was last updated"
      - name: order_sum
        data_type: double
        description: "Total order amount"
      - name: description
        data_type: varchar
        description: "Order description or notes"

  - name: orders_history_scd2
    description: "SCD Type 2 table - full history of all order changes with temporal validity"
    config:
      contract:
        enforced: true
    columns:
      - name: ingested_at
        data_type: timestamp(6) with time zone
        description: "When this record was ingested into the data lake"
        tests:
          - not_null
      - name: source_file
        data_type: varchar
        description: "Source CSV file name"
      - name: audit_event_id
        data_type: bigint
        description: "Unique identifier for the audit event"
        tests:
          - not_null
      - name: audit_operation
        data_type: varchar
        description: "Type of operation: I (Insert), U (Update), D (Delete)"
        tests:
          - not_null
          - accepted_values:
              values: ['I', 'U', 'D']
      - name: valid_from
        data_type: timestamp(6) with time zone
        description: "Timestamp when this version became active"
        tests:
          - not_null
      - name: valid_to
        data_type: timestamp(6) with time zone
        description: "Timestamp when this version was superseded (NULL = current)"
      - name: is_current
        data_type: boolean
        description: "Boolean flag: TRUE for the latest version"
        tests:
          - not_null
      - name: is_deleted
        data_type: boolean
        description: "Boolean flag: TRUE if this is a delete operation"
        tests:
          - not_null
      - name: tbl_schema
        data_type: varchar
        description: "Schema of the source table"
        tests:
          - not_null
      - name: tbl_name
        data_type: varchar
        description: "Name of the source table"
        tests:
          - not_null
      - name: order_id
        data_type: integer
        description: "Order identifier (not unique - multiple versions exist)"
        tests:
          - not_null
      - name: order_timestamp
        data_type: timestamp(6) with time zone
        description: "When the order was placed"
      - name: created_at
        data_type: timestamp(6) with time zone
        description: "When the order record was created"
      - name: updated_at
        data_type: timestamp(6) with time zone
        description: "When the order record was last updated"
      - name: order_sum
        data_type: double
        description: "Total order amount"
      - name: description
        data_type: varchar
        description: "Order description or notes"