version: 2

models:
  - name: stg_ecomm_audit_log_dml_orders_flattened
    description: "Staging table for Orders audit log dml data flattened"

  - name: stg_ecomm_audit_log_dml
    description: "Staging table for audit log dml data"
    config:
      contract:
        enforced: true
    columns:
      - name: ingested_at
        data_type: timestamp
      - name: source_file
        data_type: varchar
      - name: audit_event_id
        data_type: BIGINT
        tests:
          - not_null
          - unique
      - name: audit_timestamp
        data_type: timestamp
        tests:
          - not_null
      - name: audit_operation
        data_type: varchar
      - name: tbl_schema
        data_type: varchar
      - name: tbl_name
        data_type: varchar
      - name: raw_data
        data_type: varchar
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - audit_event_id
            - audit_timestamp
